### ISSUE TITLE
Use react, redux, etc

### ISSUE THREAD

**Issue by saiichihashimoto** [kogg/hovercards#18]
- [x] All state held in redux
  - [x] top-frame and every-frame share state
  - [x] background as well
- [x] Follow file structure in https://github.com/teamkogg/hovercards/issues/18#issuecomment-234405048
- [x] Loading screen
- [x] Discussions
  - [x] Use discussions given via content
  - [x] twitter comments are different than all the rest #23 
- [x] All experience and view related javascript in react
  - [x] Things _outside_ the hovercard (like it's triggered and such) might not fit into react. That's OK
  - [x] Expanding comments
  - [x] Carousel arrow keys
- [x] Error screen
- [x] Retry request after authentication
- [x] All html in react
- [x] All css in react
- [x] Put analytics back
  - [x] Follow analytics convention provided by @marcomarandiz 
- [x] Fix styles (might become it's own issue) #79

[ractive.js](http://www.ractivejs.org/) is not fun. [react](https://facebook.github.io/react/) is. This would make life so much better.

This is mostly a giant cleanup/rewrite.

Blocked by #10 & #17. Helps fulfill #22.
This'll need the list of requirements to grow substantially to include what the extension already behaves like (e.g. mutes on hover, allows switching discussion, loads discussions in order then allows picking them on demand, etc.) and needs to be pretty thorough. This more or less rewrites most of hovercards; we want to make sure there's no regressions. Adding new things or changing old things will be completely denied, unless it makes doing this task easier and changes nothing for the user (e.g. standardizing the analytics). **Definitely** will have to release to a small group and watch them very carefully.
